/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import ticket.booking.entities.Ticket;
import ticket.booking.entities.Train;
import ticket.booking.entities.User;
import ticket.booking.service.UserService;
import ticket.booking.utils.UserServiceUtils;

import java.io.IOException;
import java.util.*;

public class App {

    public static void main(String[] args) {
        System.out.println("Running Train Booking System");
        Scanner sc=new Scanner(System.in);
        int option=0;
        UserService userService;
        try {
            userService=new UserService();
        } catch (IOException e) {
            System.out.println("There is something wrong");
            return;
        }

        while(option!=7){
            System.out.println("Choose option");
            System.out.println("1. Sign up");
            System.out.println("2. Login");
            System.out.println("3. Fetch Bookings");
            System.out.println("4. Search Trains");
            System.out.println("5. Book a Seat");
            System.out.println("6. Cancel my Booking");
            System.out.println("7. Exit the App");
            option=sc.nextInt();
            Train trainToBookSeat;
            switch(option){
                case 1:
                      System.out.println("Enter the username to signup.");
                      String nameToSignUp=sc.next();
                      System.out.println("Enter the password to signup.");
                      String passwordToSignUp=sc.next();
                      User userToSignUp=new User(nameToSignUp, UUID.randomUUID().toString(), UserServiceUtils.hashPassword(passwordToSignUp),new ArrayList<Ticket>());
                      userService.signUp(userToSignUp);
                      break;
                
                case 2:
                    System.out.println("Enter the username to login");
                    String nameToLogin=sc.next();
                    System.out.println("Enter the password to login");
                    String passwordToLogin=sc.next();
                    User userToLogin=new User(nameToLogin,null, UserServiceUtils.hashPassword(passwordToLogin),new ArrayList<Ticket>());
                    userService.loginUser(userToLogin);
                    break;

                case 3:
                    System.out.println("Your Bookings are: ");
                    userService.fetchBooking();
                    break;

                case 4:
                      System.out.println("Enter Source ");
                      String source=sc.next();
                    System.out.println("Enter destination");
                      String destination=sc.next();
                      List<Train> trains=userService.getTrains(source,destination);
                      int index=1;
                      for(Train train:trains){
                          System.out.println(index+" "+train.getTrainId());
                          for(Map.Entry<String, Date>entry:train.getStationTimes().entrySet()){
                              System.out.println("station : "+entry.getKey()+" time: "+entry.getValue());
                          }
                      }
                      System.out.println("Select a Train by typing 1,2,3...");
                      trainToBookSeat=trains.get(sc.nextInt());
                      break;

                case 5:
                    System.out.println("Enter Source ");
                    String sourceStation=sc.next();
                    System.out.println("Enter destination");
                    String destinationStation=sc.next();
                    List<Train> trainss = userBookingService.getTrains(sourceStation, dest);
                    int indexx = 1;
                    for (Train t: trainss){
                        System.out.println(indexx+" Train id : "+t.getTrainId());
                        for (Map.Entry<String, Date> entry: t.getStationTimes().entrySet()){
                            System.out.println("station "+entry.getKey()+" time: "+entry.getValue());
                        }
                    }
                    System.out.println("Select a train by typing 1,2,3...");
                    int trainSelectedForBooking = trainss.get(scanner.nextInt());
                    break;

                case 6:
                    break;

            }
        }
    }
}
